FROM temporalio/auto-setup:1.14.3

COPY temporal-cluster/server/dynamicconfig.yaml /etc/temporal/dynamicconfig.yaml
COPY temporal-cluster/server/auto-setup/auto-setup-override.sh /etc/temporal/auto-setup.sh
